name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - CLIENTS_AMOUNT=1
    volumes:
      - ./server/config.ini:/config.ini
    networks:
      - testing_net

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_NAME=DummyName1
      - CLI_SURNAME=DummySurname1
      - CLI_ID_NUMBER=12345678
      - CLI_DATE_OF_BIRTH=1999-07-10
      - CLI_BET_NUMBER=1111
    volumes:
      - ./client/config.yaml:/config.yaml
      - ./.data/agency-1.csv:/.data/agency.csv
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
